name: projeto-git CI
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    env:
      PIPENV_NO_INHERIT: 1
      PIPENV_IGNORE_VIRTUALENVS: 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          architecture: x64

      - name: Install dependencies
        run: |
          pip install -r -requirements-dev.txt


      - name: Lint with flake8
        run: |
        
          flake8 .
